### ISSUE TITLE
Correct obvious OCR errors in the pre-processing stage (Go)

### ISSUE THREAD

**Issue by lmullen** [lmullen/legal-modernism#36]
We want to create a table of the most obvious OCR errors. This should be a CSV file with the OCR error as one column and the correction as the other. We are only going to correct straightforward find and replace. 

Note that these corrections have to happen in both Python and Go, so it is helpful to have the data separate from the function.

**Comment by kfunk074** [comment]
[Common OCR Errors.xlsx](https://github.com/lmullen/legal-modernism/files/7530153/Common.OCR.Errors.xlsx)

Here is a start on the common errors found in Pomeroy and Dillon treatises.

**Comment by kfunk074** [comment]
We are aiming to replace words instead of units where disambiguous. So corrected Tcx to Tex and Cmn to Crim independently will also correct "Tcx. Cmn. App." to "Tex. Crim. App." In some cases, we must include the whole unit, so N. II. becomes N. H.

These corrections are only disambiguous within the context of a citation. That is, it would be optimal if the find and replace were only run only within the reporter fields found by our general reg ex citation detector.

**Comment by lmullen** [comment]
The OCR errors CSV is in the repo at `data/ocr-errors.csv`. https://github.com/lmullen/legal-modernism/blob/eyecite/data/ocr-errors.csv

**Comment by kfunk074** [comment]
I can update the OCR errors CSV if I can get a list of general regex citations in an English treatise: https://github.com/lmullen/legal-modernism/issues/42#issuecomment-967751321

**Comment by lmullen** [comment]
The code for this works fine now. It's just a question of compiling the list of corrections. That's really a separate issue.
